export const copy = {
  title: "Users",
  subtitle:
    "Who can sign in. Admins configure services and users; sales work the prospect list.",
  addUser: "Add user",
  loadError: "Could not load users.",
  empty: "No users yet.",
  emptyBody: "Add the people who should sign in to LeadRadar.",
  columns: {
    name: "Name",
    email: "Email",
    role: "Role",
    status: "Status",
    lastSignIn: "Last sign-in",
  },
  noName: "No name",
  you: "You",
  active: "Active",
  deactivated: "Deactivated",
  never: "Never",
  edit: "Edit",
  editLabel: (name: string) => `Edit ${name}`,
  form: {
    email: "Work email",
    fullName: "Full name",
    role: "Role",
    password: "Password",
    passwordHelp:
      "At least 10 characters. Share it with the user; they cannot reset it themselves.",
    newPassword: "New password",
    newPasswordHelp:
      "Leave empty to keep the current password. At least 10 characters.",
    active: "Active",
    activeHelp: "Deactivated users can no longer sign in.",
    // The session token keeps the old role until the user signs in again (backend auth/router.py:141-144).
    roleHelp: "A new role takes effect the next time they sign in.",
    selfRole: "You can't change your own role.",
    selfActive: "You can't deactivate your own account.",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    create: "Add user",
    creating: "Adding…",
  },
  addTitle: "Add user",
  addDescription: "The user signs in with this email and password.",
  editTitle: "Edit user",
  validation: {
    email: "Enter a valid email address",
    password: "Use at least 10 characters",
    duplicate: "A user with this email already exists.",
  },
  toast: {
    added: "User added",
    saved: "User saved",
  },
}
